"""
Seed data for Requirements v1.7 - Production-ready initial data.

This file contains the complete pricing structure from the v1.7 requirements,
including all 26 SKUs with proper categorization, pricing, hours, and acceptance criteria.
"""

from datetime import date

# Pricing Version
PRICING_VERSION = {
    "VersionNumber": "2025.1",
    "Description": "Requirements v1.7 - Restructured SKUs with earmarked pricing",
    "EffectiveDate": date(2025, 1, 1),
    "ExpirationDate": None,
    "IsCurrent": True,
    "IsLocked": False,
    "CreatedBy": "System Seed",
}

# SKU Definitions (26 total)
SKU_DEFINITIONS = [
    # Organization Setup (3 SKUs - All Earmarked, All $23,920)
    {
        "SKUCode": "ORG-BASIC",
        "Name": "Basic Teller Setup",
        "Description": "Initial Teller system setup for basic organizations. Includes system configuration, admin user creation, and basic settings application for straightforward implementations.",
        "Category": "Service",
        "FixedPrice": 23920.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 10,
        "EarmarkedStatus": True,
        "EstimatedHours": 104,
        "AcceptanceCriteria": "System configured; admin user created; basic settings applied; user can log in and navigate core features",
    },
    {
        "SKUCode": "ORG-MED",
        "Name": "Enterprise Medium Setup",
        "Description": "Enhanced setup for medium-sized enterprises. Includes advanced configuration, multiple admin users, role-based access control, and integration with organizational systems.",
        "Category": "Service",
        "FixedPrice": 23920.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 11,
        "EarmarkedStatus": True,
        "EstimatedHours": 104,
        "AcceptanceCriteria": "System configured; multiple admin users created; advanced settings applied; integrations configured; security policies implemented",
    },
    {
        "SKUCode": "ORG-LARGE",
        "Name": "Enterprise Large Setup",
        "Description": "Comprehensive setup for large enterprises. Includes full feature enablement, complex organizational hierarchy, advanced integrations, SSO configuration, and comprehensive security setup.",
        "Category": "Service",
        "FixedPrice": 23920.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 12,
        "EarmarkedStatus": True,
        "EstimatedHours": 104,
        "AcceptanceCriteria": "System configured; multiple admin users; full feature set enabled; SSO configured; organizational hierarchy established; all integrations tested",
    },
    # Training (3 SKUs)
    {
        "SKUCode": "TRN-SUITE",
        "Name": "Teller Training Suite",
        "Description": "Comprehensive training covering all aspects of Teller usage. Includes Usage, Management, Configuration, IT Administration, and Report Writing modules. Saves $9,200 vs individual courses.",
        "Category": "Training",
        "FixedPrice": 12880.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 20,
        "EarmarkedStatus": False,
        "EstimatedHours": 56,
        "AcceptanceCriteria": "All 5 training modules delivered; attendees pass usage assessment; documentation provided; Q&A session completed",
    },
    {
        "SKUCode": "TRN-REV",
        "Name": "Revenue Submission Training",
        "Description": "Training for staff on using revenue submission features. Covers workflow, data entry, validation, reporting, and troubleshooting common issues.",
        "Category": "Training",
        "FixedPrice": 1840.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 21,
        "EarmarkedStatus": False,
        "EstimatedHours": 8,
        "AcceptanceCriteria": "Revenue submission training delivered; users can submit revenue; validation rules understood; reporting demonstrated",
    },
    {
        "SKUCode": "TRN-ORG",
        "Name": "Organizational Administration Training",
        "Description": "Training for administrators on organizational management features. Covers user management, permissions, organizational hierarchy, and administrative workflows.",
        "Category": "Training",
        "FixedPrice": 920.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 22,
        "EarmarkedStatus": False,
        "EstimatedHours": 4,
        "AcceptanceCriteria": "Org admin training delivered; admins can manage org settings; user management demonstrated; permissions configured",
    },
    # Hardware (4 SKUs)
    {
        "SKUCode": "TT-100",
        "Name": "Teller Terminal Standard",
        "Description": "Standard teller terminal with touchscreen, receipt printer, and barcode scanner. Includes mounting hardware and cables.",
        "Category": "Hardware",
        "FixedPrice": 2500.00,
        "RequiresQuantity": True,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 30,
        "EarmarkedStatus": False,
        "EstimatedHours": None,
        "AcceptanceCriteria": "Hardware delivered; physically installed; connected to network; basic functionality verified",
    },
    {
        "SKUCode": "TT-200",
        "Name": "Teller Terminal Premium",
        "Description": "Premium teller terminal with dual monitors, high-speed receipt printer, signature capture, and advanced barcode/QR scanner. Enterprise-grade construction.",
        "Category": "Hardware",
        "FixedPrice": 3800.00,
        "RequiresQuantity": True,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 31,
        "EarmarkedStatus": False,
        "EstimatedHours": None,
        "AcceptanceCriteria": "Premium hardware delivered; dual monitors configured; signature capture tested; scanner functionality verified",
    },
    {
        "SKUCode": "SCAN-100",
        "Name": "Document Scanner",
        "Description": "High-speed document scanner for check imaging and document capture. Includes OCR software and TWAIN drivers.",
        "Category": "Hardware",
        "FixedPrice": 1200.00,
        "RequiresQuantity": True,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 32,
        "EarmarkedStatus": False,
        "EstimatedHours": None,
        "AcceptanceCriteria": "Scanner delivered; drivers installed; OCR software configured; test scans successful",
    },
    {
        "SKUCode": "PRINT-100",
        "Name": "Receipt Printer",
        "Description": "Thermal receipt printer with auto-cutter. Compatible with all Teller terminal models. Includes paper rolls starter kit.",
        "Category": "Hardware",
        "FixedPrice": 450.00,
        "RequiresQuantity": True,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 33,
        "EarmarkedStatus": False,
        "EstimatedHours": None,
        "AcceptanceCriteria": "Printer delivered; connected to terminal; test receipts printed; auto-cutter functioning",
    },
    # Services (12 SKUs)
    {
        "SKUCode": "CHK-RECOG",
        "Name": "Check Recognition & ICL",
        "Description": "Implementation of check recognition and Image Cash Letter (ICL) processing. Includes system configuration, testing with production check images, and compliance validation.",
        "Category": "Service",
        "FixedPrice": 3680.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": True,
        "SortOrder": 40,
        "EarmarkedStatus": True,
        "EstimatedHours": 16,
        "AcceptanceCriteria": "Check recognition configured; ICL files generated successfully; test transactions processed; compliance verified",
    },
    {
        "SKUCode": "DATA-MIG",
        "Name": "Data Migration Service",
        "Description": "Professional data migration from legacy systems. Includes data mapping, transformation, validation, and reconciliation services.",
        "Category": "Service",
        "FixedPrice": 9200.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": True,
        "SortOrder": 41,
        "EarmarkedStatus": False,
        "EstimatedHours": 40,
        "AcceptanceCriteria": "Data mapping complete; migration executed; validation reports generated; reconciliation confirmed; stakeholders approved",
    },
    {
        "SKUCode": "CUSTOM-DEV",
        "Name": "Custom Development",
        "Description": "Custom feature development and system modifications. Billed per 40-hour block. Includes requirements analysis, development, testing, and deployment.",
        "Category": "Service",
        "FixedPrice": 9200.00,
        "RequiresQuantity": True,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": True,
        "SortOrder": 42,
        "EarmarkedStatus": False,
        "EstimatedHours": 40,
        "AcceptanceCriteria": "Requirements documented; custom code developed; unit tests passed; stakeholder acceptance obtained; deployed to production",
    },
    {
        "SKUCode": "REPORT-DEV",
        "Name": "Custom Report Development",
        "Description": "Development of custom reports and dashboards. Includes requirements gathering, data source mapping, report design, and user training.",
        "Category": "Service",
        "FixedPrice": 2300.00,
        "RequiresQuantity": True,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": True,
        "SortOrder": 43,
        "EarmarkedStatus": False,
        "EstimatedHours": 10,
        "AcceptanceCriteria": "Report requirements approved; data sources validated; report generates successfully; users trained; documentation provided",
    },
    {
        "SKUCode": "PM-STD",
        "Name": "Project Management (Standard)",
        "Description": "Standard project management services for straightforward implementations. Includes planning, coordination, status reporting, and stakeholder communication.",
        "Category": "ProjectManagement",
        "FixedPrice": 9200.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 50,
        "EarmarkedStatus": False,
        "EstimatedHours": 40,
        "AcceptanceCriteria": "Project plan delivered; regular status meetings held; milestones tracked; stakeholders informed; project closed successfully",
    },
    {
        "SKUCode": "PM-ENT",
        "Name": "Project Management (Enterprise)",
        "Description": "Enterprise project management for complex, multi-phase implementations. Includes detailed planning, risk management, change control, resource coordination, and executive reporting.",
        "Category": "ProjectManagement",
        "FixedPrice": 28520.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 51,
        "EarmarkedStatus": False,
        "EstimatedHours": 124,
        "AcceptanceCriteria": "Comprehensive project plan; risk register maintained; change control process; executive dashboards; successful delivery",
    },
    {
        "SKUCode": "CREDIT-EXIST",
        "Name": "Credit Integration - Existing",
        "Description": "Integration with client's existing credit decision system. Includes API integration, data mapping, testing, and production validation.",
        "Category": "CreditIntegration",
        "FixedPrice": 9200.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": True,
        "SortOrder": 60,
        "EarmarkedStatus": True,
        "EstimatedHours": 40,
        "AcceptanceCriteria": "Credit API integrated; test transactions successful; data mapping validated; production verified; error handling tested",
    },
    {
        "SKUCode": "CREDIT-NEW",
        "Name": "Credit Integration - New",
        "Description": "Setup and integration of new credit decision system. Includes system provisioning, configuration, API integration, comprehensive testing, and user training.",
        "Category": "CreditIntegration",
        "FixedPrice": 28520.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": True,
        "SortOrder": 61,
        "EarmarkedStatus": True,
        "EstimatedHours": 124,
        "AcceptanceCriteria": "New credit system provisioned; API integrated; test transactions successful; users trained; production cutover complete",
    },
    {
        "SKUCode": "WF-SUBMIT",
        "Name": "Workflow Submission Setup",
        "Description": "Enable workflow submission capabilities for automated document routing and approval workflows. Configuration and testing of workflow rules and notifications.",
        "Category": "WorkflowSubmission",
        "FixedPrice": None,  # TBD
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": True,
        "SortOrder": 62,
        "EarmarkedStatus": True,
        "EstimatedHours": None,  # TBD
        "AcceptanceCriteria": "Workflow submission configured; test workflow submitted successfully; approval routing verified; notifications working",
    },
    {
        "SKUCode": "TO-MATURE",
        "Name": "Teller Online Integration Add-on (Mature)",
        "Description": "Integration with mature, well-documented third-party online banking system. Standard API implementation with existing documentation and support.",
        "Category": "Service",
        "FixedPrice": 2760.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": True,
        "SortOrder": 70,
        "EarmarkedStatus": False,
        "EstimatedHours": 12,
        "AcceptanceCriteria": "API integration complete; test transactions successful; error handling verified; production cutover complete",
    },
    {
        "SKUCode": "TO-NEW",
        "Name": "Teller Online Integration Add-on (New)",
        "Description": "Integration with newer third-party system requiring additional development effort. Includes custom API development, enhanced error handling, and extended testing.",
        "Category": "Service",
        "FixedPrice": 6440.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": True,
        "SortOrder": 71,
        "EarmarkedStatus": False,
        "EstimatedHours": 28,
        "AcceptanceCriteria": "API integration complete; custom development deployed; test transactions successful; comprehensive testing passed; production verified",
    },
    {
        "SKUCode": "TO-REDIRECT",
        "Name": "Teller Online Third-Party Redirect",
        "Description": "Full redirect integration with third-party online banking system. Complex implementation including SSO, seamless user experience, session management, and comprehensive security.",
        "Category": "Service",
        "FixedPrice": 28520.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": True,
        "SortOrder": 72,
        "EarmarkedStatus": False,
        "EstimatedHours": 124,
        "AcceptanceCriteria": "Redirect flow implemented; SSO configured; user experience seamless; session management working; production verified; security audit passed",
    },
    # Travel (1 SKU with zone calculation)
    {
        "SKUCode": "TRAVEL",
        "Name": "Travel & Expenses",
        "Description": "Travel expenses for on-site implementation, training, and support. Calculated based on travel zone rates including mileage, per diem, airfare, hotel, and rental car.",
        "Category": "Travel",
        "FixedPrice": None,  # Calculated per zone
        "RequiresQuantity": True,
        "RequiresTravelZone": True,
        "RequiresConfiguration": False,
        "IsActive": True,
        "SortOrder": 80,
        "EarmarkedStatus": False,
        "EstimatedHours": None,  # Variable based on trip
        "AcceptanceCriteria": "Travel days specified; expenses documented; receipts provided; within approved travel zone rates",
    },
]

# Deprecated SKUs (from v1.5 - kept for historical quotes)
DEPRECATED_SKUS = [
    {
        "SKUCode": "TRN-USAGE",
        "Name": "Teller Usage Training",
        "Description": "[DEPRECATED] Basic usage training - replaced by Training Suite",
        "Category": "Training",
        "FixedPrice": 920.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": False,
        "SortOrder": 999,
        "EarmarkedStatus": False,
        "EstimatedHours": 4,
        "AcceptanceCriteria": "Training delivered",
    },
    {
        "SKUCode": "TRN-MGMT",
        "Name": "Teller Management Training",
        "Description": "[DEPRECATED] Management training - replaced by Training Suite",
        "Category": "Training",
        "FixedPrice": 920.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": False,
        "SortOrder": 999,
        "EarmarkedStatus": False,
        "EstimatedHours": 4,
        "AcceptanceCriteria": "Training delivered",
    },
    {
        "SKUCode": "TRN-CONFIG",
        "Name": "Teller Configuration Training",
        "Description": "[DEPRECATED] Configuration training - replaced by Training Suite",
        "Category": "Training",
        "FixedPrice": 2760.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": False,
        "SortOrder": 999,
        "EarmarkedStatus": False,
        "EstimatedHours": 12,
        "AcceptanceCriteria": "Training delivered",
    },
    {
        "SKUCode": "TRN-ITADMIN",
        "Name": "Teller IT Administration Training",
        "Description": "[DEPRECATED] IT admin training - replaced by Training Suite",
        "Category": "Training",
        "FixedPrice": 2760.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": False,
        "SortOrder": 999,
        "EarmarkedStatus": False,
        "EstimatedHours": 12,
        "AcceptanceCriteria": "Training delivered",
    },
    {
        "SKUCode": "TRN-REPORT",
        "Name": "Teller Report Writing Training",
        "Description": "[DEPRECATED] Report writing training - replaced by Training Suite",
        "Category": "Training",
        "FixedPrice": 2760.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": False,
        "IsActive": False,
        "SortOrder": 999,
        "EarmarkedStatus": False,
        "EstimatedHours": 12,
        "AcceptanceCriteria": "Training delivered",
    },
    {
        "SKUCode": "TO-ADDON",
        "Name": "Teller Online Integration Add-on",
        "Description": "[DEPRECATED] Generic Teller Online addon - replaced by tiered options (Mature/New/Redirect)",
        "Category": "Service",
        "FixedPrice": 4600.00,
        "RequiresQuantity": False,
        "RequiresTravelZone": False,
        "RequiresConfiguration": True,
        "IsActive": False,
        "SortOrder": 999,
        "EarmarkedStatus": False,
        "EstimatedHours": 20,
        "AcceptanceCriteria": "Integration complete",
    },
]

# Referrers (Global - not versioned)
REFERRERS = [
    {
        "ReferrerName": "ABC Financial Partners",
        "StandardRate": 5.00,
        "IsActive": True,
    },
    {
        "ReferrerName": "Tech Solutions Group",
        "StandardRate": 7.50,
        "IsActive": True,
    },
    {
        "ReferrerName": "Direct Sales (No Referrer)",
        "StandardRate": 0.00,
        "IsActive": True,
    },
]

# Travel Zones
TRAVEL_ZONES = [
    {
        "ZoneCode": "ZONE-A",
        "Name": "Local (< 50 miles)",
        "Description": "Local travel within 50 miles. Mileage reimbursement only, no lodging required.",
        "MileageRate": 0.67,
        "DailyRate": 150.00,
        "HourlyRate": 230.00,
        "OnsiteDaysIncluded": 0,
        "IsActive": True,
        "SortOrder": 1,
    },
    {
        "ZoneCode": "ZONE-B",
        "Name": "Regional (50-250 miles)",
        "Description": "Regional travel requiring overnight stay. Includes hotel and meals per diem.",
        "MileageRate": 0.67,
        "DailyRate": 200.00,
        "HourlyRate": 230.00,
        "OnsiteDaysIncluded": 1,
        "IsActive": True,
        "SortOrder": 2,
    },
    {
        "ZoneCode": "ZONE-C",
        "Name": "National (250+ miles)",
        "Description": "National travel requiring airfare. Includes flight, hotel, rental car, and full per diem.",
        "MileageRate": 0.67,
        "DailyRate": 250.00,
        "HourlyRate": 230.00,
        "OnsiteDaysIncluded": 2,
        "IsActive": True,
        "SortOrder": 3,
    },
]

# SaaS Products
SAAS_PRODUCTS = [
    {
        "ProductCode": "SAAS-CORE",
        "Name": "Teller Core Platform",
        "Description": "Base Teller platform with core teller transaction processing capabilities. Required for all implementations.",
        "Category": "Core",
        "PricingModel": "Tiered",
        "Tier1Min": 1,
        "Tier1Max": 10,
        "Tier1Price": 125.00,
        "Tier2Min": 11,
        "Tier2Max": 50,
        "Tier2Price": 100.00,
        "Tier3Min": 51,
        "Tier3Max": None,  # Unlimited
        "Tier3Price": 85.00,
        "IsActive": True,
        "IsRequired": True,
        "SortOrder": 1,
    },
    {
        "ProductCode": "SAAS-MOBILE",
        "Name": "Teller Mobile Access",
        "Description": "Mobile app access for tellers and supervisors. Includes iOS and Android native apps with full offline capability.",
        "Category": "Optional",
        "PricingModel": "Tiered",
        "Tier1Min": 1,
        "Tier1Max": 10,
        "Tier1Price": 25.00,
        "Tier2Min": 11,
        "Tier2Max": 50,
        "Tier2Price": 20.00,
        "Tier3Min": 51,
        "Tier3Max": None,
        "Tier3Price": 15.00,
        "IsActive": True,
        "IsRequired": False,
        "SortOrder": 2,
    },
    {
        "ProductCode": "SAAS-ANALYTICS",
        "Name": "Advanced Analytics & Reporting",
        "Description": "Advanced analytics dashboard with custom reports, data visualization, and predictive analytics powered by AI.",
        "Category": "Optional",
        "PricingModel": "Tiered",
        "Tier1Min": 1,
        "Tier1Max": 10,
        "Tier1Price": 50.00,
        "Tier2Min": 11,
        "Tier2Max": 50,
        "Tier2Price": 40.00,
        "Tier3Min": 51,
        "Tier3Max": None,
        "Tier3Price": 30.00,
        "IsActive": True,
        "IsRequired": False,
        "SortOrder": 3,
    },
]

# Text Snippets
TEXT_SNIPPETS = [
    {
        "SnippetKey": "INTRO_STANDARD",
        "SnippetLabel": "Standard Introduction",
        "Content": "Thank you for considering our Teller implementation services. This quote provides a comprehensive overview of the hardware, software, and services required for your organization's successful Teller deployment.",
        "Category": "Proposal",
        "SortOrder": 1,
        "IsActive": True,
    },
    {
        "SnippetKey": "INTRO_ENTERPRISE",
        "SnippetLabel": "Enterprise Introduction",
        "Content": "Thank you for considering our enterprise Teller implementation services. This quote reflects our comprehensive approach to large-scale deployments, including advanced integration capabilities, dedicated project management, and extended support services tailored to your organization's complex requirements.",
        "Category": "Proposal",
        "SortOrder": 2,
        "IsActive": True,
    },
    {
        "SnippetKey": "TERMS_PAYMENT",
        "SnippetLabel": "Payment Terms",
        "Content": "Payment terms: 50% due upon contract signing, 30% due upon system deployment, and 20% due upon project completion and acceptance. All payments are due within 30 days of invoice date.",
        "Category": "Legal",
        "SortOrder": 10,
        "IsActive": True,
    },
    {
        "SnippetKey": "TERMS_WARRANTY",
        "SnippetLabel": "Warranty Terms",
        "Content": "All hardware carries a manufacturer's warranty of 1 year from date of installation. Software and implementation services include 90 days of post-implementation support at no additional charge. Extended warranty and support packages are available separately.",
        "Category": "Legal",
        "SortOrder": 11,
        "IsActive": True,
    },
    {
        "SnippetKey": "SCOPE_ASSUMPTIONS",
        "SnippetLabel": "Project Assumptions",
        "Content": "This quote assumes: (1) Client will provide timely access to necessary systems and personnel; (2) Client infrastructure meets minimum technical requirements; (3) Scope changes will be managed through formal change control process; (4) Travel expenses will be billed at actual costs per approved travel zone rates.",
        "Category": "Legal",
        "SortOrder": 20,
        "IsActive": True,
    },
    {
        "SnippetKey": "FOOTER_CONTACT",
        "SnippetLabel": "Contact Information",
        "Content": "For questions regarding this quote, please contact our sales team at sales@tellerquoting.com or call (555) 123-4567. We look forward to partnering with your organization.",
        "Category": "Proposal",
        "SortOrder": 30,
        "IsActive": True,
    },
]
