"""Add all tables for v1.9 schema

Revision ID: 0f3e7b4204dc
Revises: 41f6688b0f09
Create Date: 2025-12-08 14:39:03.841012

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f3e7b4204dc"
down_revision: str | Sequence[str] | None = "41f6688b0f09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "AuditLogs",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "Timestamp",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the change occurred",
        ),
        sa.Column(
            "UserId",
            sa.String(length=255),
            nullable=False,
            comment="User who made the change (email or ID)",
        ),
        sa.Column(
            "Action", sa.String(length=10), nullable=False, comment="CREATE, UPDATE, or DELETE"
        ),
        sa.Column(
            "TableName", sa.String(length=100), nullable=False, comment="Table that was modified"
        ),
        sa.Column(
            "RecordId",
            sa.String(length=255),
            nullable=False,
            comment="Primary key of the modified record",
        ),
        sa.Column(
            "OldValues",
            sa.JSON(),
            nullable=True,
            comment="JSON snapshot of old values (NULL for CREATE)",
        ),
        sa.Column(
            "NewValues",
            sa.JSON(),
            nullable=True,
            comment="JSON snapshot of new values (NULL for DELETE)",
        ),
        sa.Column(
            "Changes", sa.Text(), nullable=True, comment="Human-readable summary of what changed"
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_AuditLogs")),
    )
    op.create_index(op.f("ix_AuditLogs_Action"), "AuditLogs", ["Action"], unique=False)
    op.create_index(op.f("ix_AuditLogs_RecordId"), "AuditLogs", ["RecordId"], unique=False)
    op.create_index(op.f("ix_AuditLogs_TableName"), "AuditLogs", ["TableName"], unique=False)
    op.create_index(op.f("ix_AuditLogs_Timestamp"), "AuditLogs", ["Timestamp"], unique=False)
    op.create_index(op.f("ix_AuditLogs_UserId"), "AuditLogs", ["UserId"], unique=False)
    op.create_table(
        "MatureIntegrations",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "IntegrationCode",
            sa.String(length=50),
            nullable=False,
            comment="Unique integration identifier code",
        ),
        sa.Column(
            "SystemName",
            sa.String(length=255),
            nullable=False,
            comment="Name of the integrated system",
        ),
        sa.Column(
            "Vendor", sa.String(length=255), nullable=True, comment="Vendor/provider of the system"
        ),
        sa.Column(
            "Comments", sa.Text(), nullable=True, comment="Additional notes about the integration"
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if integration is no longer offered",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when integration was added",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when integration was last updated",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_MatureIntegrations")),
    )
    op.create_index(
        op.f("ix_MatureIntegrations_IntegrationCode"),
        "MatureIntegrations",
        ["IntegrationCode"],
        unique=True,
    )
    op.create_table(
        "PricingVersions",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "VersionNumber",
            sa.String(length=20),
            nullable=False,
            comment="Version identifier (e.g., '2025.1', '2025.2')",
        ),
        sa.Column(
            "Description",
            sa.Text(),
            nullable=True,
            comment="Description of changes in this version",
        ),
        sa.Column(
            "EffectiveDate",
            sa.Date(),
            nullable=False,
            comment="Date when this pricing becomes effective",
        ),
        sa.Column(
            "ExpirationDate",
            sa.Date(),
            nullable=True,
            comment="Date when this pricing expires (null if current)",
        ),
        sa.Column(
            "CreatedBy",
            sa.String(length=255),
            nullable=False,
            comment="User who created this version",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when version was created",
        ),
        sa.Column(
            "IsCurrent",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if this is the current active version",
        ),
        sa.Column(
            "IsLocked",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if version is locked (used in quotes)",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_PricingVersions")),
    )
    op.create_index(
        op.f("ix_PricingVersions_VersionNumber"), "PricingVersions", ["VersionNumber"], unique=True
    )
    op.create_table(
        "Quotes",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "QuoteNumber",
            sa.String(length=50),
            nullable=False,
            comment="Quote number, e.g. Q-2025-0001",
        ),
        sa.Column(
            "ClientName", sa.String(length=255), nullable=False, comment="Client organization name"
        ),
        sa.Column(
            "ClientOrganization",
            sa.String(length=255),
            nullable=True,
            comment="Client organization type/details",
        ),
        sa.Column(
            "CreatedBy", sa.String(length=255), nullable=False, comment="User who created the quote"
        ),
        sa.Column("CreatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("UpdatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "Status",
            sa.String(length=50),
            nullable=False,
            comment="DRAFT, SENT, ACCEPTED, DECLINED",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_Quotes")),
    )
    op.create_index(op.f("ix_Quotes_ClientName"), "Quotes", ["ClientName"], unique=False)
    op.create_index(op.f("ix_Quotes_CreatedBy"), "Quotes", ["CreatedBy"], unique=False)
    op.create_index(op.f("ix_Quotes_QuoteNumber"), "Quotes", ["QuoteNumber"], unique=True)
    op.create_table(
        "Referrers",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "ReferrerName",
            sa.String(length=255),
            nullable=False,
            comment="Name of the referrer/partner",
        ),
        sa.Column(
            "StandardRate",
            sa.DECIMAL(precision=5, scale=2),
            nullable=False,
            comment="Standard commission rate as percentage (e.g., 5.00 for 5%)",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if referrer is no longer active",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when referrer was added",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when referrer was last updated",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_Referrers")),
    )
    op.create_index(op.f("ix_Referrers_ReferrerName"), "Referrers", ["ReferrerName"], unique=False)
    op.create_table(
        "SKUDefinitions",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("PricingVersionId", sa.UUID(), nullable=False, comment="Link to pricing version"),
        sa.Column(
            "SKUCode",
            sa.String(length=50),
            nullable=False,
            comment="Unique SKU identifier (e.g., 'TT-100', 'TR-200')",
        ),
        sa.Column("Name", sa.String(length=255), nullable=False, comment="Display name for SKU"),
        sa.Column(
            "Description", sa.Text(), nullable=True, comment="Detailed description of the SKU"
        ),
        sa.Column(
            "Category",
            sa.String(length=50),
            nullable=False,
            comment="SKU category (e.g., 'Hardware', 'Service', 'Travel')",
        ),
        sa.Column(
            "FixedPrice",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Fixed price if applicable (NULL for calculated pricing)",
        ),
        sa.Column(
            "RequiresQuantity",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="True if quantity is required for this SKU",
        ),
        sa.Column(
            "RequiresTravelZone",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if travel zone selection is required",
        ),
        sa.Column(
            "RequiresConfiguration",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if additional configuration is required",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if SKU is discontinued",
        ),
        sa.Column(
            "SortOrder",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Display order for UI",
        ),
        sa.Column(
            "EarmarkedStatus",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if pricing is subject to change during project refinement",
        ),
        sa.Column(
            "EstimatedHours",
            sa.Integer(),
            nullable=True,
            comment="Estimated hours for this SKU (NULL for TBD)",
        ),
        sa.Column(
            "AcceptanceCriteria",
            sa.Text(),
            nullable=True,
            comment="Acceptance criteria for deliverable completion",
        ),
        sa.Column(
            "ScopeDescription",
            sa.Text(),
            nullable=True,
            comment="What's included in this SKU (for Implementation Plan)",
        ),
        sa.Column(
            "Deliverables",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="List of specific deliverables as JSON array",
        ),
        sa.Column(
            "TypicalDuration",
            sa.Integer(),
            nullable=True,
            comment="Typical duration in weeks (for schedule building)",
        ),
        sa.Column(
            "QuickbooksCategory",
            sa.String(length=100),
            nullable=True,
            comment="Category/account code for Quickbooks",
        ),
        sa.Column(
            "Dependencies",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Required prerequisite SKUs as JSON array of SKU IDs",
        ),
        sa.Column(
            "IsRepeatable",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Can be added multiple times (e.g., integrations)",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when SKU was created",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when SKU was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["PricingVersionId"],
            ["PricingVersions.Id"],
            name=op.f("fk_SKUDefinitions_PricingVersionId_PricingVersions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_SKUDefinitions")),
    )
    op.create_index(
        op.f("ix_SKUDefinitions_Category"), "SKUDefinitions", ["Category"], unique=False
    )
    op.create_index(
        op.f("ix_SKUDefinitions_PricingVersionId"),
        "SKUDefinitions",
        ["PricingVersionId"],
        unique=False,
    )
    op.create_index(op.f("ix_SKUDefinitions_SKUCode"), "SKUDefinitions", ["SKUCode"], unique=False)
    op.create_table(
        "SaaSProducts",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("PricingVersionId", sa.UUID(), nullable=False, comment="Link to pricing version"),
        sa.Column(
            "ProductCode",
            sa.String(length=50),
            nullable=False,
            comment="Unique product identifier (e.g., 'SAAS-001', 'SAAS-002')",
        ),
        sa.Column(
            "Name", sa.String(length=255), nullable=False, comment="Display name for SaaS product"
        ),
        sa.Column(
            "Description", sa.Text(), nullable=True, comment="Detailed description of the product"
        ),
        sa.Column(
            "Category",
            sa.String(length=50),
            nullable=False,
            comment="Product category (e.g., 'Core', 'Optional', 'Add-on')",
        ),
        sa.Column(
            "PricingModel",
            sa.String(length=50),
            nullable=False,
            comment="Pricing model type (e.g., 'Tiered', 'Flat', 'Usage-based')",
        ),
        sa.Column("Tier1Min", sa.Integer(), nullable=False, comment="Minimum users for tier 1"),
        sa.Column("Tier1Max", sa.Integer(), nullable=False, comment="Maximum users for tier 1"),
        sa.Column(
            "Tier1Price",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Price per user for tier 1",
        ),
        sa.Column("Tier2Min", sa.Integer(), nullable=True, comment="Minimum users for tier 2"),
        sa.Column("Tier2Max", sa.Integer(), nullable=True, comment="Maximum users for tier 2"),
        sa.Column(
            "Tier2Price",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Price per user for tier 2",
        ),
        sa.Column("Tier3Min", sa.Integer(), nullable=True, comment="Minimum users for tier 3"),
        sa.Column(
            "Tier3Max",
            sa.Integer(),
            nullable=True,
            comment="Maximum users for tier 3 (null for unlimited)",
        ),
        sa.Column(
            "Tier3Price",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Price per user for tier 3",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if product is discontinued",
        ),
        sa.Column(
            "IsRequired",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if product is required in all quotes",
        ),
        sa.Column(
            "SortOrder",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Display order for UI",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when product was created",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when product was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["PricingVersionId"],
            ["PricingVersions.Id"],
            name=op.f("fk_SaaSProducts_PricingVersionId_PricingVersions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_SaaSProducts")),
    )
    op.create_index(op.f("ix_SaaSProducts_Category"), "SaaSProducts", ["Category"], unique=False)
    op.create_index(
        op.f("ix_SaaSProducts_PricingVersionId"), "SaaSProducts", ["PricingVersionId"], unique=False
    )
    op.create_index(
        op.f("ix_SaaSProducts_ProductCode"), "SaaSProducts", ["ProductCode"], unique=False
    )
    op.create_table(
        "TextSnippets",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("PricingVersionId", sa.UUID(), nullable=False, comment="Link to pricing version"),
        sa.Column(
            "SnippetKey",
            sa.String(length=100),
            nullable=False,
            comment="Unique key identifier for the snippet (e.g., 'INTRO_TEXT', 'TERMS')",
        ),
        sa.Column(
            "SnippetLabel",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable label for the snippet",
        ),
        sa.Column(
            "Content", sa.Text(), nullable=False, comment="The actual text content of the snippet"
        ),
        sa.Column(
            "Category",
            sa.String(length=50),
            nullable=False,
            comment="Category of snippet (e.g., 'OrderForm', 'Proposal', 'Legal')",
        ),
        sa.Column(
            "SortOrder",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Display order for UI",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if snippet is deprecated",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when snippet was created",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when snippet was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["PricingVersionId"],
            ["PricingVersions.Id"],
            name=op.f("fk_TextSnippets_PricingVersionId_PricingVersions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_TextSnippets")),
    )
    op.create_index(op.f("ix_TextSnippets_Category"), "TextSnippets", ["Category"], unique=False)
    op.create_index(
        op.f("ix_TextSnippets_PricingVersionId"), "TextSnippets", ["PricingVersionId"], unique=False
    )
    op.create_index(
        op.f("ix_TextSnippets_SnippetKey"), "TextSnippets", ["SnippetKey"], unique=False
    )
    op.create_table(
        "TravelZones",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("PricingVersionId", sa.UUID(), nullable=False, comment="Link to pricing version"),
        sa.Column(
            "ZoneCode",
            sa.String(length=50),
            nullable=False,
            comment="Unique zone identifier (e.g., 'ZONE-1', 'ZONE-2')",
        ),
        sa.Column(
            "Name", sa.String(length=255), nullable=False, comment="Display name for travel zone"
        ),
        sa.Column(
            "Description",
            sa.Text(),
            nullable=True,
            comment="Detailed description of the zone (e.g., 'United States, Canada, Caribbean')",
        ),
        sa.Column(
            "MileageRate",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Rate per mile for this zone",
        ),
        sa.Column(
            "DailyRate",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Daily rate for travel in this zone",
        ),
        sa.Column(
            "HourlyRate",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Hourly rate for on-site work in this zone",
        ),
        sa.Column(
            "OnsiteDaysIncluded",
            sa.Integer(),
            nullable=False,
            comment="Number of on-site days included in base price",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if zone is no longer offered",
        ),
        sa.Column(
            "SortOrder",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Display order for UI",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when zone was created",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when zone was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["PricingVersionId"],
            ["PricingVersions.Id"],
            name=op.f("fk_TravelZones_PricingVersionId_PricingVersions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_TravelZones")),
    )
    op.create_index(
        op.f("ix_TravelZones_PricingVersionId"), "TravelZones", ["PricingVersionId"], unique=False
    )
    op.create_index(op.f("ix_TravelZones_ZoneCode"), "TravelZones", ["ZoneCode"], unique=False)
    op.create_table(
        "ApplicationModules",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("PricingVersionId", sa.UUID(), nullable=False, comment="Link to pricing version"),
        sa.Column(
            "ModuleCode",
            sa.String(length=50),
            nullable=False,
            comment="Unique module identifier (e.g., CHECK_RECOGNITION, REVENUE_SUBMISSION)",
        ),
        sa.Column(
            "ModuleName", sa.String(length=255), nullable=False, comment="Display name for module"
        ),
        sa.Column("Description", sa.Text(), nullable=True, comment="Description of the module"),
        sa.Column(
            "SaaSProductId",
            sa.UUID(),
            nullable=True,
            comment="Link to SaaS product for this module (if applicable)",
        ),
        sa.Column(
            "RequiredSKUs",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Auto-add these SKUs when module enabled (array of SKU IDs)",
        ),
        sa.Column(
            "SubParameters",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Configuration questions/parameters for this module",
        ),
        sa.Column(
            "SelectionRules",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Rules for determining which SKUs based on sub-parameter values",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if module is discontinued",
        ),
        sa.Column(
            "SortOrder",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Display order for UI",
        ),
        sa.Column("CreatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("UpdatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["PricingVersionId"],
            ["PricingVersions.Id"],
            name=op.f("fk_ApplicationModules_PricingVersionId_PricingVersions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["SaaSProductId"],
            ["SaaSProducts.Id"],
            name=op.f("fk_ApplicationModules_SaaSProductId_SaaSProducts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_ApplicationModules")),
    )
    op.create_index(
        op.f("ix_ApplicationModules_ModuleCode"), "ApplicationModules", ["ModuleCode"], unique=False
    )
    op.create_index(
        op.f("ix_ApplicationModules_PricingVersionId"),
        "ApplicationModules",
        ["PricingVersionId"],
        unique=False,
    )
    op.create_table(
        "QuoteVersions",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("QuoteId", sa.UUID(), nullable=False),
        sa.Column(
            "VersionNumber",
            sa.Integer(),
            nullable=False,
            comment="Sequential version number: 1, 2, 3...",
        ),
        sa.Column(
            "VersionDescription",
            sa.Text(),
            nullable=True,
            comment="Description of changes in this version",
        ),
        sa.Column("PricingVersionId", sa.UUID(), nullable=False),
        sa.Column(
            "ClientData",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
            comment="Client details: name, address, contacts, population, location",
        ),
        sa.Column("ProjectionYears", sa.Integer(), nullable=False),
        sa.Column(
            "EscalationModel",
            sa.String(length=50),
            nullable=False,
            comment="STANDARD_4PCT, CPI, MULTI_YEAR_FREEZE",
        ),
        sa.Column("MultiYearFreezeYears", sa.Integer(), nullable=True),
        sa.Column("LevelLoadingEnabled", sa.Boolean(), nullable=False),
        sa.Column("TellerPaymentsEnabled", sa.Boolean(), nullable=False),
        sa.Column(
            "DiscountConfig",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Discount configuration: saas_year1_pct, saas_all_years_pct, setup_fixed, setup_pct",
        ),
        sa.Column("ReferrerId", sa.UUID(), nullable=True),
        sa.Column("ReferralRateOverride", sa.Numeric(), nullable=True),
        sa.Column(
            "MilestoneStyle",
            sa.String(length=50),
            nullable=False,
            comment="FIXED_MONTHLY, DELIVERABLE_BASED",
        ),
        sa.Column("InitialPaymentPercentage", sa.Numeric(), nullable=False),
        sa.Column("ProjectDurationMonths", sa.Integer(), nullable=False),
        sa.Column("TravelZoneId", sa.UUID(), nullable=True),
        sa.Column(
            "TravelConfig",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Array of trips with days, people, overrides",
        ),
        sa.Column("TotalSaaSMonthly", sa.Numeric(), nullable=True),
        sa.Column("TotalSaaSAnnualYear1", sa.Numeric(), nullable=True),
        sa.Column("TotalSetupPackages", sa.Numeric(), nullable=True),
        sa.Column("TotalTravel", sa.Numeric(), nullable=True),
        sa.Column("TotalContractedAmount", sa.Numeric(), nullable=True),
        sa.Column("CreatedBy", sa.String(length=255), nullable=False),
        sa.Column("CreatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "VersionStatus", sa.String(length=50), nullable=False, comment="DRAFT, SENT, ACCEPTED"
        ),
        sa.ForeignKeyConstraint(
            ["PricingVersionId"],
            ["PricingVersions.Id"],
            name=op.f("fk_QuoteVersions_PricingVersionId_PricingVersions"),
        ),
        sa.ForeignKeyConstraint(
            ["QuoteId"],
            ["Quotes.Id"],
            name=op.f("fk_QuoteVersions_QuoteId_Quotes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ReferrerId"], ["Referrers.Id"], name=op.f("fk_QuoteVersions_ReferrerId_Referrers")
        ),
        sa.ForeignKeyConstraint(
            ["TravelZoneId"],
            ["TravelZones.Id"],
            name=op.f("fk_QuoteVersions_TravelZoneId_TravelZones"),
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_QuoteVersions")),
    )
    op.create_index(
        op.f("ix_QuoteVersions_PricingVersionId"),
        "QuoteVersions",
        ["PricingVersionId"],
        unique=False,
    )
    op.create_index(op.f("ix_QuoteVersions_QuoteId"), "QuoteVersions", ["QuoteId"], unique=False)
    op.create_table(
        "QuoteVersionSaaSProducts",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("QuoteVersionId", sa.UUID(), nullable=False),
        sa.Column("SaaSProductId", sa.UUID(), nullable=False),
        sa.Column(
            "Quantity", sa.Numeric(), nullable=False, comment="Volume input for tiered pricing"
        ),
        sa.Column("CalculatedMonthlyPrice", sa.Numeric(), nullable=False),
        sa.Column("Notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["QuoteVersionId"],
            ["QuoteVersions.Id"],
            name=op.f("fk_QuoteVersionSaaSProducts_QuoteVersionId_QuoteVersions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["SaaSProductId"],
            ["SaaSProducts.Id"],
            name=op.f("fk_QuoteVersionSaaSProducts_SaaSProductId_SaaSProducts"),
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_QuoteVersionSaaSProducts")),
    )
    op.create_table(
        "QuoteVersionSetupPackages",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("QuoteVersionId", sa.UUID(), nullable=False),
        sa.Column("SKUDefinitionId", sa.UUID(), nullable=False),
        sa.Column("Quantity", sa.Integer(), nullable=False),
        sa.Column("CalculatedPrice", sa.Numeric(), nullable=False),
        sa.Column("CustomScopeNotes", sa.Text(), nullable=True),
        sa.Column("SequenceOrder", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["QuoteVersionId"],
            ["QuoteVersions.Id"],
            name=op.f("fk_QuoteVersionSetupPackages_QuoteVersionId_QuoteVersions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["SKUDefinitionId"],
            ["SKUDefinitions.Id"],
            name=op.f("fk_QuoteVersionSetupPackages_SKUDefinitionId_SKUDefinitions"),
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_QuoteVersionSetupPackages")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("QuoteVersionSetupPackages")
    op.drop_table("QuoteVersionSaaSProducts")
    op.drop_index(op.f("ix_QuoteVersions_QuoteId"), table_name="QuoteVersions")
    op.drop_index(op.f("ix_QuoteVersions_PricingVersionId"), table_name="QuoteVersions")
    op.drop_table("QuoteVersions")
    op.drop_index(op.f("ix_ApplicationModules_PricingVersionId"), table_name="ApplicationModules")
    op.drop_index(op.f("ix_ApplicationModules_ModuleCode"), table_name="ApplicationModules")
    op.drop_table("ApplicationModules")
    op.drop_index(op.f("ix_TravelZones_ZoneCode"), table_name="TravelZones")
    op.drop_index(op.f("ix_TravelZones_PricingVersionId"), table_name="TravelZones")
    op.drop_table("TravelZones")
    op.drop_index(op.f("ix_TextSnippets_SnippetKey"), table_name="TextSnippets")
    op.drop_index(op.f("ix_TextSnippets_PricingVersionId"), table_name="TextSnippets")
    op.drop_index(op.f("ix_TextSnippets_Category"), table_name="TextSnippets")
    op.drop_table("TextSnippets")
    op.drop_index(op.f("ix_SaaSProducts_ProductCode"), table_name="SaaSProducts")
    op.drop_index(op.f("ix_SaaSProducts_PricingVersionId"), table_name="SaaSProducts")
    op.drop_index(op.f("ix_SaaSProducts_Category"), table_name="SaaSProducts")
    op.drop_table("SaaSProducts")
    op.drop_index(op.f("ix_SKUDefinitions_SKUCode"), table_name="SKUDefinitions")
    op.drop_index(op.f("ix_SKUDefinitions_PricingVersionId"), table_name="SKUDefinitions")
    op.drop_index(op.f("ix_SKUDefinitions_Category"), table_name="SKUDefinitions")
    op.drop_table("SKUDefinitions")
    op.drop_index(op.f("ix_Referrers_ReferrerName"), table_name="Referrers")
    op.drop_table("Referrers")
    op.drop_index(op.f("ix_Quotes_QuoteNumber"), table_name="Quotes")
    op.drop_index(op.f("ix_Quotes_CreatedBy"), table_name="Quotes")
    op.drop_index(op.f("ix_Quotes_ClientName"), table_name="Quotes")
    op.drop_table("Quotes")
    op.drop_index(op.f("ix_PricingVersions_VersionNumber"), table_name="PricingVersions")
    op.drop_table("PricingVersions")
    op.drop_index(op.f("ix_MatureIntegrations_IntegrationCode"), table_name="MatureIntegrations")
    op.drop_table("MatureIntegrations")
    op.drop_index(op.f("ix_AuditLogs_UserId"), table_name="AuditLogs")
    op.drop_index(op.f("ix_AuditLogs_Timestamp"), table_name="AuditLogs")
    op.drop_index(op.f("ix_AuditLogs_TableName"), table_name="AuditLogs")
    op.drop_index(op.f("ix_AuditLogs_RecordId"), table_name="AuditLogs")
    op.drop_index(op.f("ix_AuditLogs_Action"), table_name="AuditLogs")
    op.drop_table("AuditLogs")
    # ### end Alembic commands ###
