"""Add SKUDefinitions table

Revision ID: 10f585dc0a4b
Revises: 9cfdb020636e
Create Date: 2025-12-03 20:41:48.747155

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10f585dc0a4b"
down_revision: str | Sequence[str] | None = "9cfdb020636e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SKUDefinitions",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("PricingVersionId", sa.UUID(), nullable=False, comment="Link to pricing version"),
        sa.Column(
            "SKUCode",
            sa.String(length=50),
            nullable=False,
            comment="Unique SKU identifier (e.g., 'TT-100', 'TR-200')",
        ),
        sa.Column("Name", sa.String(length=255), nullable=False, comment="Display name for SKU"),
        sa.Column(
            "Description", sa.Text(), nullable=True, comment="Detailed description of the SKU"
        ),
        sa.Column(
            "Category",
            sa.String(length=50),
            nullable=False,
            comment="SKU category (e.g., 'Hardware', 'Service', 'Travel')",
        ),
        sa.Column(
            "FixedPrice",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Fixed price if applicable (NULL for calculated pricing)",
        ),
        sa.Column(
            "RequiresQuantity",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="True if quantity is required for this SKU",
        ),
        sa.Column(
            "RequiresTravelZone",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if travel zone selection is required",
        ),
        sa.Column(
            "RequiresConfiguration",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if additional configuration is required",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if SKU is discontinued",
        ),
        sa.Column(
            "SortOrder",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Display order for UI",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when SKU was created",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when SKU was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["PricingVersionId"],
            ["PricingVersions.Id"],
            name=op.f("fk_SKUDefinitions_PricingVersionId_PricingVersions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_SKUDefinitions")),
    )
    op.create_index(
        op.f("ix_SKUDefinitions_Category"), "SKUDefinitions", ["Category"], unique=False
    )
    op.create_index(
        op.f("ix_SKUDefinitions_PricingVersionId"),
        "SKUDefinitions",
        ["PricingVersionId"],
        unique=False,
    )
    op.create_index(op.f("ix_SKUDefinitions_SKUCode"), "SKUDefinitions", ["SKUCode"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_SKUDefinitions_SKUCode"), table_name="SKUDefinitions")
    op.drop_index(op.f("ix_SKUDefinitions_PricingVersionId"), table_name="SKUDefinitions")
    op.drop_index(op.f("ix_SKUDefinitions_Category"), table_name="SKUDefinitions")
    op.drop_table("SKUDefinitions")
    # ### end Alembic commands ###
