"""Add SaaSProducts table

Revision ID: 379268e353ac
Revises: 10f585dc0a4b
Create Date: 2025-12-03 20:43:22.034327

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "379268e353ac"
down_revision: str | Sequence[str] | None = "10f585dc0a4b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SaaSProducts",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("PricingVersionId", sa.UUID(), nullable=False, comment="Link to pricing version"),
        sa.Column(
            "ProductCode",
            sa.String(length=50),
            nullable=False,
            comment="Unique product identifier (e.g., 'SAAS-001', 'SAAS-002')",
        ),
        sa.Column(
            "Name", sa.String(length=255), nullable=False, comment="Display name for SaaS product"
        ),
        sa.Column(
            "Description", sa.Text(), nullable=True, comment="Detailed description of the product"
        ),
        sa.Column(
            "Category",
            sa.String(length=50),
            nullable=False,
            comment="Product category (e.g., 'Core', 'Optional', 'Add-on')",
        ),
        sa.Column(
            "PricingModel",
            sa.String(length=50),
            nullable=False,
            comment="Pricing model type (e.g., 'Tiered', 'Flat', 'Usage-based')",
        ),
        sa.Column("Tier1Min", sa.Integer(), nullable=False, comment="Minimum users for tier 1"),
        sa.Column("Tier1Max", sa.Integer(), nullable=False, comment="Maximum users for tier 1"),
        sa.Column(
            "Tier1Price",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Price per user for tier 1",
        ),
        sa.Column("Tier2Min", sa.Integer(), nullable=True, comment="Minimum users for tier 2"),
        sa.Column("Tier2Max", sa.Integer(), nullable=True, comment="Maximum users for tier 2"),
        sa.Column(
            "Tier2Price",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Price per user for tier 2",
        ),
        sa.Column("Tier3Min", sa.Integer(), nullable=True, comment="Minimum users for tier 3"),
        sa.Column(
            "Tier3Max",
            sa.Integer(),
            nullable=True,
            comment="Maximum users for tier 3 (null for unlimited)",
        ),
        sa.Column(
            "Tier3Price",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Price per user for tier 3",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if product is discontinued",
        ),
        sa.Column(
            "IsRequired",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if product is required in all quotes",
        ),
        sa.Column(
            "SortOrder",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Display order for UI",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when product was created",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when product was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["PricingVersionId"],
            ["PricingVersions.Id"],
            name=op.f("fk_SaaSProducts_PricingVersionId_PricingVersions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_SaaSProducts")),
    )
    op.create_index(op.f("ix_SaaSProducts_Category"), "SaaSProducts", ["Category"], unique=False)
    op.create_index(
        op.f("ix_SaaSProducts_PricingVersionId"), "SaaSProducts", ["PricingVersionId"], unique=False
    )
    op.create_index(
        op.f("ix_SaaSProducts_ProductCode"), "SaaSProducts", ["ProductCode"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_SaaSProducts_ProductCode"), table_name="SaaSProducts")
    op.drop_index(op.f("ix_SaaSProducts_PricingVersionId"), table_name="SaaSProducts")
    op.drop_index(op.f("ix_SaaSProducts_Category"), table_name="SaaSProducts")
    op.drop_table("SaaSProducts")
    # ### end Alembic commands ###
