"""Add MatureIntegrations, Referrers, and TextSnippets tables

Revision ID: 77857d070f6f
Revises: f9f1501abd23
Create Date: 2025-12-03 20:56:05.207729

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77857d070f6f"
down_revision: str | Sequence[str] | None = "f9f1501abd23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "MatureIntegrations",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "IntegrationCode",
            sa.String(length=50),
            nullable=False,
            comment="Unique integration identifier code",
        ),
        sa.Column(
            "SystemName",
            sa.String(length=255),
            nullable=False,
            comment="Name of the integrated system",
        ),
        sa.Column(
            "Vendor", sa.String(length=255), nullable=True, comment="Vendor/provider of the system"
        ),
        sa.Column(
            "Comments", sa.Text(), nullable=True, comment="Additional notes about the integration"
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if integration is no longer offered",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when integration was added",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when integration was last updated",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_MatureIntegrations")),
    )
    op.create_index(
        op.f("ix_MatureIntegrations_IntegrationCode"),
        "MatureIntegrations",
        ["IntegrationCode"],
        unique=True,
    )
    op.create_table(
        "Referrers",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "ReferrerName",
            sa.String(length=255),
            nullable=False,
            comment="Name of the referrer/partner",
        ),
        sa.Column(
            "StandardRate",
            sa.DECIMAL(precision=5, scale=2),
            nullable=False,
            comment="Standard commission rate as percentage (e.g., 5.00 for 5%)",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if referrer is no longer active",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when referrer was added",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when referrer was last updated",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_Referrers")),
    )
    op.create_index(op.f("ix_Referrers_ReferrerName"), "Referrers", ["ReferrerName"], unique=False)
    op.create_table(
        "TextSnippets",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("PricingVersionId", sa.UUID(), nullable=False, comment="Link to pricing version"),
        sa.Column(
            "SnippetKey",
            sa.String(length=100),
            nullable=False,
            comment="Unique key identifier for the snippet (e.g., 'INTRO_TEXT', 'TERMS')",
        ),
        sa.Column(
            "SnippetLabel",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable label for the snippet",
        ),
        sa.Column(
            "Content", sa.Text(), nullable=False, comment="The actual text content of the snippet"
        ),
        sa.Column(
            "Category",
            sa.String(length=50),
            nullable=False,
            comment="Category of snippet (e.g., 'OrderForm', 'Proposal', 'Legal')",
        ),
        sa.Column(
            "SortOrder",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Display order for UI",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if snippet is deprecated",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when snippet was created",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when snippet was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["PricingVersionId"],
            ["PricingVersions.Id"],
            name=op.f("fk_TextSnippets_PricingVersionId_PricingVersions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_TextSnippets")),
    )
    op.create_index(op.f("ix_TextSnippets_Category"), "TextSnippets", ["Category"], unique=False)
    op.create_index(
        op.f("ix_TextSnippets_PricingVersionId"), "TextSnippets", ["PricingVersionId"], unique=False
    )
    op.create_index(
        op.f("ix_TextSnippets_SnippetKey"), "TextSnippets", ["SnippetKey"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_TextSnippets_SnippetKey"), table_name="TextSnippets")
    op.drop_index(op.f("ix_TextSnippets_PricingVersionId"), table_name="TextSnippets")
    op.drop_index(op.f("ix_TextSnippets_Category"), table_name="TextSnippets")
    op.drop_table("TextSnippets")
    op.drop_index(op.f("ix_Referrers_ReferrerName"), table_name="Referrers")
    op.drop_table("Referrers")
    op.drop_index(op.f("ix_MatureIntegrations_IntegrationCode"), table_name="MatureIntegrations")
    op.drop_table("MatureIntegrations")
    # ### end Alembic commands ###
