"""Rename columns to PascalCase

Revision ID: 9cfdb020636e
Revises: fb345d7f952f
Create Date: 2025-12-03 19:44:40.388832

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cfdb020636e"
down_revision: str | Sequence[str] | None = "fb345d7f952f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "PricingVersions",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "VersionNumber",
            sa.String(length=20),
            nullable=False,
            comment="Version identifier (e.g., '2025.1', '2025.2')",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "Description",
            sa.Text(),
            nullable=True,
            comment="Description of changes in this version",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "EffectiveDate",
            sa.Date(),
            nullable=False,
            comment="Date when this pricing becomes effective",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "ExpirationDate",
            sa.Date(),
            nullable=True,
            comment="Date when this pricing expires (null if current)",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "CreatedBy",
            sa.String(length=255),
            nullable=False,
            comment="User who created this version",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when version was created",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "IsCurrent",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if this is the current active version",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "IsLocked",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if version is locked (used in quotes)",
        ),
    )
    op.drop_index(op.f("ix_PricingVersions_version_number"), table_name="PricingVersions")
    op.create_index(
        op.f("ix_PricingVersions_VersionNumber"), "PricingVersions", ["VersionNumber"], unique=True
    )
    op.drop_column("PricingVersions", "is_locked")
    op.drop_column("PricingVersions", "description")
    op.drop_column("PricingVersions", "is_current")
    op.drop_column("PricingVersions", "expiration_date")
    op.drop_column("PricingVersions", "effective_date")
    op.drop_column("PricingVersions", "created_by")
    op.drop_column("PricingVersions", "id")
    op.drop_column("PricingVersions", "created_at")
    op.drop_column("PricingVersions", "version_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "PricingVersions",
        sa.Column(
            "version_number",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
            comment="Version identifier (e.g., '2025.1', '2025.2')",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Timestamp when version was created",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "created_by",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="User who created this version",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "effective_date",
            sa.DATE(),
            autoincrement=False,
            nullable=False,
            comment="Date when this pricing becomes effective",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "expiration_date",
            sa.DATE(),
            autoincrement=False,
            nullable=True,
            comment="Date when this pricing expires (null if current)",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "is_current",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
            comment="True if this is the current active version",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "description",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Description of changes in this version",
        ),
    )
    op.add_column(
        "PricingVersions",
        sa.Column(
            "is_locked",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
            comment="True if version is locked (used in quotes)",
        ),
    )
    op.drop_index(op.f("ix_PricingVersions_VersionNumber"), table_name="PricingVersions")
    op.create_index(
        op.f("ix_PricingVersions_version_number"),
        "PricingVersions",
        ["version_number"],
        unique=True,
    )
    op.drop_column("PricingVersions", "IsLocked")
    op.drop_column("PricingVersions", "IsCurrent")
    op.drop_column("PricingVersions", "CreatedAt")
    op.drop_column("PricingVersions", "CreatedBy")
    op.drop_column("PricingVersions", "ExpirationDate")
    op.drop_column("PricingVersions", "EffectiveDate")
    op.drop_column("PricingVersions", "Description")
    op.drop_column("PricingVersions", "VersionNumber")
    op.drop_column("PricingVersions", "Id")
    # ### end Alembic commands ###
