"""Add TravelZones table

Revision ID: f9f1501abd23
Revises: 379268e353ac
Create Date: 2025-12-03 20:44:22.733477

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9f1501abd23"
down_revision: str | Sequence[str] | None = "379268e353ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "TravelZones",
        sa.Column("Id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("PricingVersionId", sa.UUID(), nullable=False, comment="Link to pricing version"),
        sa.Column(
            "ZoneCode",
            sa.String(length=50),
            nullable=False,
            comment="Unique zone identifier (e.g., 'ZONE-1', 'ZONE-2')",
        ),
        sa.Column(
            "Name", sa.String(length=255), nullable=False, comment="Display name for travel zone"
        ),
        sa.Column(
            "Description",
            sa.Text(),
            nullable=True,
            comment="Detailed description of the zone (e.g., 'United States, Canada, Caribbean')",
        ),
        sa.Column(
            "MileageRate",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Rate per mile for this zone",
        ),
        sa.Column(
            "DailyRate",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Daily rate for travel in this zone",
        ),
        sa.Column(
            "HourlyRate",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Hourly rate for on-site work in this zone",
        ),
        sa.Column(
            "OnsiteDaysIncluded",
            sa.Integer(),
            nullable=False,
            comment="Number of on-site days included in base price",
        ),
        sa.Column(
            "IsActive",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="False if zone is no longer offered",
        ),
        sa.Column(
            "SortOrder",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Display order for UI",
        ),
        sa.Column(
            "CreatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when zone was created",
        ),
        sa.Column(
            "UpdatedAt",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when zone was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["PricingVersionId"],
            ["PricingVersions.Id"],
            name=op.f("fk_TravelZones_PricingVersionId_PricingVersions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_TravelZones")),
    )
    op.create_index(
        op.f("ix_TravelZones_PricingVersionId"), "TravelZones", ["PricingVersionId"], unique=False
    )
    op.create_index(op.f("ix_TravelZones_ZoneCode"), "TravelZones", ["ZoneCode"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_TravelZones_ZoneCode"), table_name="TravelZones")
    op.drop_index(op.f("ix_TravelZones_PricingVersionId"), table_name="TravelZones")
    op.drop_table("TravelZones")
    # ### end Alembic commands ###
