"""Add PricingVersions table

Revision ID: fb345d7f952f
Revises:
Create Date: 2025-12-03 17:51:01.241173

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb345d7f952f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "PricingVersions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "version_number",
            sa.String(length=20),
            nullable=False,
            comment="Version identifier (e.g., '2025.1', '2025.2')",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Description of changes in this version",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=False,
            comment="Date when this pricing becomes effective",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="Date when this pricing expires (null if current)",
        ),
        sa.Column(
            "created_by",
            sa.String(length=255),
            nullable=False,
            comment="User who created this version",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when version was created",
        ),
        sa.Column(
            "is_current",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if this is the current active version",
        ),
        sa.Column(
            "is_locked",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="True if version is locked (used in quotes)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_PricingVersions")),
    )
    op.create_index(
        op.f("ix_PricingVersions_version_number"),
        "PricingVersions",
        ["version_number"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_PricingVersions_version_number"), table_name="PricingVersions")
    op.drop_table("PricingVersions")
    # ### end Alembic commands ###
